server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/jpa"
    username: root
    password: abcd@356
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true